### ISSUE TITLE
Wondering about the status of jekyll-metaweblog

### ISSUE THREAD

**Issue by efc** [tominsam/jekyll-metaweblog#8]
Tom, just discovered this today, well behind the curve! 

I think you were on the right track with jekyll-metaweblog. Seems that jekyll still really needs something like this. I'm wondering if you still use this or if you know of other work along these lines?

This code is a great help, thanks for sharing it.

**Comment by tominsam** [comment]
I don't still use it. I'm fickle. I may come back to it, however, and presumably the thing still works. It's not like the state of the metaweblog API moves very fast.

Jekyll might need something like this, but the problem is that to host it you have to solve a lot of the sort of problems that jekyll gets to entirely ignore. I don't even know _how_ to host ruby nowadays, all my expertise is 5 years out of date. :-)
